version: '3.9'
services:
  web:
    build: .
    ports:
      - 5001:5000
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - OPENAI_API_KEY
